'use client';

import type { JSX, ReactNode } from 'react';
import { motion, useReducedMotion } from 'framer-motion';
import Link from 'next/link';

import Navbar from '@/components/landing/Navbar';
import Footer from '@/components/landing/Footer';

type RevealProps = {
  children: ReactNode;
  className?: string;
  delay?: number;
};

function Reveal({ children, className = '', delay = 0 }: RevealProps): JSX.Element {
  const prefersReducedMotion = useReducedMotion();

  return (
    <motion.div
      className={className}
      initial={{ opacity: 0, y: prefersReducedMotion ? 0 : 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, amount: 0.1 }}
      transition={{
        duration: prefersReducedMotion ? 0 : 0.6,
        delay: prefersReducedMotion ? 0 : delay,
        ease: [0.22, 1, 0.36, 1],
      }}
    >
      {children}
    </motion.div>
  );
}

const sections = [
  {
    title: '1. Acceptance of Terms',
    content: `These Terms of Service ("Terms") govern your access to and use of Rivtor's website, platform, and services.

By accessing or using Rivtor, including the demo environment, design partner program, or any deployed system, you agree to be bound by these Terms.

If you do not agree, you must not use the services.`
  },
  {
    title: '2. Description of Services',
    content: `Rivtor provides AI-assisted systems designed to:

• Analyze business data and workflows
• Generate insights, recommendations, and suggested actions
• Support operational decision-making

Certain features may be:

• Experimental
• Limited in scope
• Subject to ongoing development

Rivtor does not guarantee accuracy, completeness, or business outcomes.`
  },
  {
    title: '3. Deployment Models',
    subsections: [
      {
        title: '3.1 Hosted (Rivtor Infrastructure)',
        content: `• Operated on Rivtor-managed or third-party cloud infrastructure
• May involve third-party services (e.g., AI models, databases)`
      },
      {
        title: '3.2 Private / On-Premise Deployment',
        content: `• Deployed within the client's infrastructure (e.g., AWS, Azure, GCP)
• Client retains control over data and environment`
      },
      {
        title: '3.3 Hybrid Deployment',
        content: `• Combination of Rivtor-managed and client-managed components
• Data flow depends on configuration and integration choices`
      }
    ]
  },
  {
    title: '4. Demo Environment Disclaimer',
    content: `The system available at app.rivtor.com is a demo and evaluation environment.

By using it, you acknowledge:

• It may rely on third-party infrastructure and external services
• It is not fully isolated or enterprise-grade
• It may not reflect final product capabilities

You agree not to submit sensitive, confidential, or regulated data in the demo environment.`
  },
  {
    title: '5. Design Partner & Early Access Programs',
    content: `Rivtor may grant access to selected users for evaluation, testing, or collaboration.

By participating, you acknowledge:

• Features may be incomplete, unstable, or experimental
• Outputs are for evaluation purposes only
• Rivtor may use feedback and usage data to improve the system

Participation does not guarantee future access, pricing, or features.`
  },
  {
    title: '6. User Responsibilities',
    content: `You agree to:

• Provide accurate and lawful information
• Use the platform only for legitimate business purposes
• Maintain the confidentiality of your account credentials
• Ensure that you have the rights to provide any data integrated into Rivtor

You are solely responsible for:

• Decisions made based on system outputs
• Compliance with applicable laws and regulations`
  },
  {
    title: '7. Data & Integrations',
    content: `By connecting third-party services or providing data:

• You grant Rivtor permission to access and process such data as required
• You confirm you have the legal right to share that data

Rivtor acts as a processor of data, not the owner, except as required to operate the service.`
  },
  {
    title: '8. Intellectual Property',
    subsections: [
      {
        title: '8.1 Rivtor Property',
        content: `All rights, title, and interest in:

• The platform
• Software, models, and infrastructure
• Branding and system architecture

remain the exclusive property of Rivtor.`
      },
      {
        title: '8.2 User Data',
        content: `• You retain ownership of your input data
• Rivtor does not claim ownership of your business data`
      },
      {
        title: '8.3 Outputs',
        content: `• You may use outputs generated by the system
• Rivtor retains rights to underlying systems, models, and methodologies`
      }
    ]
  },
  {
    title: '9. AI & Decision-Making Disclaimer',
    content: `Rivtor provides AI-assisted insights, recommendations, and suggested actions.

You acknowledge that:

• Outputs may be inaccurate, incomplete, or contextually incorrect
• The system does not replace professional judgment
• You must independently verify recommendations before acting

Rivtor is not responsible for any business decisions, actions, or outcomes resulting from use of the platform.`
  },
  {
    title: '10. Limitation of Liability',
    content: `To the maximum extent permitted by law, Rivtor shall not be liable for:

• Any indirect, incidental, or consequential damages
• Loss of profits, revenue, data, or business opportunities
• Decisions made based on system outputs

Use of the platform is at your own risk.`
  },
  {
    title: '11. Indemnification',
    content: `You agree to indemnify and hold harmless Rivtor from any claims, damages, or liabilities arising from:

• Your use of the platform
• Your data or integrations
• Your violation of these Terms`
  },
  {
    title: '12. Service Availability & Changes',
    content: `Rivtor may:

• Modify, update, or discontinue features at any time
• Restrict or suspend access without prior notice
• Change system architecture or deployment models

We are not obligated to maintain backward compatibility.`
  },
  {
    title: '13. Termination',
    content: `Rivtor may suspend or terminate your access:

• For violation of these Terms
• For misuse of the platform
• At its discretion (especially for demo or early access users)

Upon termination, your right to use the platform ceases immediately.`
  },
  {
    title: '14. Security & Access',
    content: `You are responsible for:

• Securing your credentials
• Managing access within your organization

Rivtor is not liable for unauthorized access resulting from user negligence.`
  },
  {
    title: '15. Third-Party Services',
    content: `Rivtor may rely on third-party services (e.g., cloud providers, AI models).

We are not responsible for:

• Performance or availability of such services
• Data handling practices of third parties

Use of such services is subject to their respective terms.`
  },
  {
    title: '16. Governing Law',
    content: `These Terms shall be governed by and interpreted in accordance with the laws of India.

Any disputes shall be subject to the jurisdiction of courts located in [Insert City/State].`
  },
  {
    title: '17. Changes to Terms',
    content: `We may update these Terms from time to time.

Continued use of the platform after changes constitutes acceptance of the updated Terms.`
  },
  {
    title: '18. Contact Information',
    content: `For any questions regarding these Terms:

• Email: legal@rivtor.com
• Company Name: Rivtor Technologies Private Limited
• Address: [Insert Address]`
  },
  {
    title: '19. Acknowledgment',
    content: `By using Rivtor, you confirm that:

• You understand the experimental nature of certain features
• You accept the limitations of AI-generated outputs
• You agree to these Terms and associated Privacy Policy
• You explicitly accept these Terms during onboarding or first login`
  }
];

export default function TermsPage(): JSX.Element {
  return (
    <main className="rv-landing-v4">
      <Navbar />

      {/* Navbar spacer */}
      <div style={{ height: '72px' }} aria-hidden="true" />

      {/* Header */}
      <section className="rv-section-v4" style={{ paddingTop: '80px', paddingBottom: '80px' }}>
        <div className="rv-container-v4">
          <Reveal>
            <div style={{ maxWidth: '800px', margin: '0 auto' }}>
              <p
                style={{
                  fontSize: '12px',
                  fontWeight: 500,
                  textTransform: 'uppercase',
                  letterSpacing: '0.12em',
                  color: 'rgba(255, 255, 255, 0.4)',
                  marginBottom: '24px',
                  fontFamily: 'var(--font-body)',
                }}
              >
                Legal
              </p>
              <h1
                style={{
                  fontSize: '48px',
                  fontWeight: 600,
                  lineHeight: '1.2',
                  letterSpacing: '-1%',
                  color: 'var(--rv-text-primary)',
                  marginBottom: '16px',
                  fontFamily: 'var(--font-headline)',
                }}
              >
                Terms of Service
              </h1>
              <p
                style={{
                  fontSize: '16px',
                  lineHeight: '1.6',
                  color: 'rgba(255, 255, 255, 0.5)',
                  margin: 0,
                  fontFamily: 'var(--font-body)',
                }}
              >
                Last Updated: January 2026
              </p>
            </div>
          </Reveal>
        </div>
      </section>

      {/* Content */}
      <section className="rv-section-v4" style={{ paddingBottom: '120px' }}>
        <div className="rv-container-v4">
          <div style={{ maxWidth: '720px', margin: '0 auto' }}>
            {sections.map((section, index) => (
              <SectionContent key={index} section={section} index={index} />
            ))}

            <Reveal delay={0.3}>
              <div
                style={{
                  marginTop: '64px',
                  paddingTop: '32px',
                  borderTop: '1px solid rgba(255, 255, 255, 0.1)',
                  textAlign: 'center',
                }}
              >
                <Link
                  href="/"
                  style={{
                    fontSize: '14px',
                    color: 'rgba(255, 255, 255, 0.6)',
                    textDecoration: 'none',
                    fontFamily: 'var(--font-body)',
                  }}
                >
                  ← Back to Home
                </Link>
              </div>
            </Reveal>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  );
}

function SectionContent({ section, index }: { section: any; index: number }) {
  return (
    <Reveal delay={index * 0.05}>
      <div style={{ marginBottom: '48px' }}>
        <h2
          style={{
            fontSize: '24px',
            fontWeight: 600,
            lineHeight: '1.3',
            letterSpacing: '-0.5%',
            color: 'var(--rv-text-primary)',
            marginBottom: '16px',
            fontFamily: 'var(--font-headline)',
          }}
        >
          {section.title}
        </h2>
        {section.subsections ? (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '32px' }}>
            {section.subsections.map((subsection: any, subIndex: number) => (
              <div key={subIndex}>
                <h3
                  style={{
                    fontSize: '18px',
                    fontWeight: 500,
                    lineHeight: '1.4',
                    color: 'var(--rv-text-primary)',
                    marginBottom: '12px',
                    fontFamily: 'var(--font-headline)',
                  }}
                >
                  {subsection.title}
                </h3>
                <div
                  style={{
                    fontSize: '16px',
                    lineHeight: '1.7',
                    color: 'rgba(255, 255, 255, 0.7)',
                    fontFamily: 'var(--font-body)',
                    whiteSpace: 'pre-line',
                  }}
                  dangerouslySetInnerHTML={{ __html: subsection.content }}
                />
              </div>
            ))}
          </div>
        ) : (
          <div
            style={{
              fontSize: '16px',
              lineHeight: '1.7',
              color: 'rgba(255, 255, 255, 0.7)',
              fontFamily: 'var(--font-body)',
              whiteSpace: 'pre-line',
            }}
            dangerouslySetInnerHTML={{ __html: section.content }}
          />
        )}
      </div>
    </Reveal>
  );
}
